hardware/urls.py
from django.urls import path
from .views import (
    HardwareList,
    export_hardware,
    HardwareSearch,
    HardwareFilter,

    HardwareControlList,
    export_hardware_control,
    HardwareControlSearch,
    HardwareControlFilter,
)

app_name = 'hardware'

urlpatterns = [
    path('hardware/list/', HardwareList.as_view(), name='hardware_list'),
    path('export/hardware/', export_hardware, name='export_hardware'),
    path('hardware/search/', HardwareSearch.as_view(), name='hardware_search'),
    path('hardware/filter/', HardwareFilter.as_view(), name='hardware_filter'),

    path('hardware/control/list/', HardwareControlList.as_view(), name='hardware_control_list'),
    path('export/hardware/control', export_hardware_control, name='export_hardware_control'),
    path('hardware/control/search/', HardwareControlSearch.as_view(), name='hardware_control_search'),
    path('hardware/control/filter/', HardwareControlFilter.as_view(), name='hardware_control_filter'),
]

sites/urls.py
from django.urls import path
from .views import (
    SiteList,
    SiteSearch,
    SiteFilter,
    # site_export,
)

app_name = 'sites'

urlpatterns = [
    path('site/list/', SiteList.as_view(), name='site_list'),
    path('site/search/', SiteSearch.as_view(), name='site_search'),
    path('site/filter/', SiteFilter.as_view(), name='site_filter'),
    # path('site/export/', site_export, name='site_export'),
]

syfboyaca4gavantel/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'SyF Hardware'

urlpatterns = [
    path('', include('users.urls', namespace='user')),
    path('hardware/', include('hardware.urls')),
    path('meetings/', include('meetings.urls')),
    path('sites/', include('sites.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hardware/forms.py
from django import forms
from django.forms import ModelForm
from .models import HardwareCategory, Hardware, HardwareControl
from . import choices


class FilterHardwareForm(ModelForm):
    hardware_category = forms.ModelChoiceField(queryset=HardwareCategory.objects.all(), required=False)
    cs_code = forms.CharField(required=False)
    supervendor_code = forms.CharField(required=False)

    class Meta:
        model = Hardware
        fields = (
            'hardware_category',
            'cs_code',
            'supervendor_code',
            'material_description',)


class FilterHardwareControlForm(ModelForm):
    hardware = forms.ModelChoiceField(queryset=Hardware.objects.all(), required=False)
    serial = forms.CharField(required=False)

    class Meta:
        model = HardwareControl
        fields = '__all__'

hardware/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
TemplateView,
ListView,
DetailView,
UpdateView,
CreateView,
DeleteView,
FormView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from .models import Hardware, HardwareControl
from .forms import FilterHardwareForm, FilterHardwareControlForm
from .resources import HardwareResource, HardwareControlResource
from django.http import HttpResponse
import operator
from django.db.models import Q
from functools import reduce


class HardwareList(LoginRequiredMixin, ListView, FormView):
    login_url = 'users:home'
    model = Hardware
    template_name = 'hardware/hardware_list.html'
    paginate_by = 15
    form_class = FilterHardwareForm

    def get_paginate_by(self, queryset):
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super(HardwareList, self).get_context_data(**kwargs)
        context['items'] = self.get_queryset
        context['all_items'] = str(Hardware.objects.all().count())
        context['paginate_by'] = self.request.GET.get('paginate_by', self.paginate_by)
        context['query'] = self.request.GET.get('qs')
        return context


class HardwareSearch(HardwareList):

    def get_queryset(self):
        queryset = super(HardwareSearch, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            queryset = queryset.filter(
                reduce(operator.and_,
                       (Q(id__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(hardware_category__name__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(cs_code__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(supervendor_code__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(material_description__icontains=q) for q in query_list))
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HardwareSearch, self).get_context_data(**kwargs)
        context['result'] = self.get_queryset().count()
        return context


class HardwareFilter(HardwareList):
    query_dict = {}

    def get_queryset(self):
        queryset = super(HardwareFilter, self).get_queryset()
        request_dict = self.request.GET.dict()
        query_dict = {k: v for k, v in request_dict.items() if v if k != 'page' if k != 'paginate_by'}
        self.query_dict = query_dict
        queryset = queryset.filter(**query_dict)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HardwareFilter, self).get_context_data(**kwargs)
        context['query_dict'] = self.query_dict
        context['result'] = self.get_queryset().count()
        return context


def export_hardware(request):
    hardware_resource = HardwareResource()
    query_dict = request.GET.dict()
    queryset = Hardware.objects.filter(**query_dict)
    dataset = hardware_resource.export(queryset)
    response = HttpResponse(dataset.xlsx, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Hardware.xlsx"'
    return response


class HardwareControlList(LoginRequiredMixin, ListView, FormView):
    login_url = 'users:home'
    model = HardwareControl
    template_name = 'hardware_control/hardware_control_list.html'
    paginate_by = 15
    form_class = FilterHardwareControlForm

    def get_paginate_by(self, queryset):
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super(HardwareControlList, self).get_context_data(**kwargs)
        context['items'] = self.get_queryset
        context['all_items'] = str(HardwareControl.objects.all().count())
        context['paginate_by'] = self.request.GET.get('paginate_by', self.paginate_by)
        context['query'] = self.request.GET.get('qs')
        return context


class HardwareControlSearch(HardwareControlList):

    def get_queryset(self):
        queryset = super(HardwareControlSearch, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            queryset = queryset.filter(
                reduce(operator.and_,
                       (Q(id__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(hardware__cs_code__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(serial__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(site__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(hardware_state__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(active_avantel__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(state_avantel__icontains=q) for q in query_list))
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HardwareControlSearch, self).get_context_data(**kwargs)
        context['result'] = self.get_queryset().count()
        return context


class HardwareControlFilter(HardwareControlList):
    query_dict = {}

    def get_queryset(self):
        queryset = super(HardwareControlFilter, self).get_queryset()
        request_dict = self.request.GET.dict()
        query_dict = {k: v for k, v in request_dict.items() if v if k != 'page' if k != 'paginate_by'}
        self.query_dict = query_dict
        queryset = queryset.filter(**query_dict)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HardwareControlFilter, self).get_context_data(**kwargs)
        context['query_dict'] = self.query_dict
        context['result'] = self.get_queryset().count()
        return context


def export_hardware_control(request):
    hardware_control_resource = HardwareControlResource()
    query_dict = request.GET.dict()
    queryset = HardwareControl.objects.filter(**query_dict)
    dataset = hardware_control_resource.export(queryset)
    response = HttpResponse(dataset.xlsx, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Hardware.xlsx"'
    return response

hardware/templates/hardware/hardware_list.html
{% extends 'base.html' %}
{% load static %}
{% load filter_tags %}
{% block title %}SyF Hardware{% endblock title %}

{% block navbar %}
{% include 'dashboard/includes/partials/navbar.html' %}
{% endblock navbar %}

{% block sidebar %}
{% include 'dashboard/includes/partials/sidebar.html' %}
{% endblock sidebar %}

{% block content_dashboard %}

<main role="main" class="">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-2 border-bottom mb-2">
    <h2 class="text-dark">Hardware</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'hardware:export_hardware' %}?{{query_dict|get_encoded_dict}}">
          <span data-feather="download"></span>
          Exportar
        </a>
      </div>
      <div class="btn-group" role="group">
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle mr-2  disabled" id="action" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span data-feather="play"></span>
          Accion
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#"></a>
          <a class="dropdown-item" href="#"></a>
        </div>
      </div>
      <div class="btn-group" role="group">
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span data-feather="calendar"></span>
          Hoy
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Created</a>
          <a class="dropdown-item" href="#">Updated</a>
        </div>
      </div>
    </div>
  </div>
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'hardware:hardware_list' %}">Hardware</a>
    </li>
  </ul>
  <div class="d-flex justify-content-end flex-wrap flex-md-nowrap align-items-center">
    {% if result %}
    found {{ result }} de  {{ all_items }} items
    {% else %}
    {% endif %}
    <a class="nav-link btn btn-light btn-sm ml-3" href="#" id="filter-toggle"><span data-feather="menu"></span> Filter</a>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-sm" id="table_hardware">
      <thead>
        {% include 'hardware/includes/partials/hardware_head.html' %}
      </thead>
      <tbody>
        {% for object in object_list %}
          {% include 'hardware/includes/partials/hardware_body.html' %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
<div class="row border-bottom d-flex justify-content-end align-items-center mr-2">
    {% include 'dashboard/includes/partials/nav_paginate.html' %}
</div>
{% endblock content_dashboard %}

{% block filter %}
{% include 'dashboard/includes/partials/filter.html' %}
{% endblock filter %}