hardware/urls.py
from django.urls import path
from .views import (
    HardwareList,
    export_hardware,
    HardwareSearch,
    HardwareFilter,

    HardwareControlList,
    export_hardware_control,
    HardwareControlSearch,
    HardwareControlFilter,
)

app_name = 'hardware'

urlpatterns = [
    path('hardware/list/', HardwareList.as_view(), name='hardware_list'),
    path('export/hardware/', export_hardware, name='export_hardware'),
    path('hardware/search/', HardwareSearch.as_view(), name='hardware_search'),
    path('hardware/filter/', HardwareFilter.as_view(), name='hardware_filter'),

    path('hardware/control/list/', HardwareControlList.as_view(), name='hardware_control_list'),
    path('export/hardware/control', export_hardware_control, name='export_hardware_control'),
    path('hardware/control/search/', HardwareControlSearch.as_view(), name='hardware_control_search'),
    path('hardware/control/filter/', HardwareControlFilter.as_view(), name='hardware_control_filter'),
]

meetings/urls.py
from django.urls import path
from .views import (
    PointList,
    PointSearch,
    PointFilter,
    # point_export,
)

app_name = 'meetings'

urlpatterns = [
    path('point/list/', PointList.as_view(), name='point_list'),
    path('point/search/', PointSearch.as_view(), name='point_search'),
    path('point/filter/', PointFilter.as_view(), name='point_filter'),
    # path('point/export/', point_export, name='point_export'),
]

sites/urls.py
from django.urls import path
from .views import (
    SiteList,
    SiteSearch,
    SiteFilter,
    # site_export,
)

app_name = 'sites'

urlpatterns = [
    path('site/list/', SiteList.as_view(), name='site_list'),
    path('site/search/', SiteSearch.as_view(), name='site_search'),
    path('site/filter/', SiteFilter.as_view(), name='site_filter'),
    # path('site/export/', site_export, name='site_export'),
]

syfboyaca4gavantel/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'SyF Hardware'

urlpatterns = [
    path('', include('users.urls', namespace='user')),
    path('hardware/', include('hardware.urls')),
    path('meetings/', include('meetings.urls')),
    path('sites/', include('sites.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import (
HomeView,
Login,
Logout,
Signin,
)

app_name = 'users'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('signin/', Signin.as_view(), name='signin'),
]

hardware/forms.py
from django import forms
from django.forms import ModelForm
from .models import HardwareCategory, Hardware, HardwareControl
from . import choices


class FilterHardwareForm(ModelForm):
    hardware_category = forms.ModelChoiceField(queryset=HardwareCategory.objects.all(), required=False)
    cs_code = forms.CharField(required=False)
    supervendor_code = forms.CharField(required=False)

    class Meta:
        model = Hardware
        fields = (
            'hardware_category',
            'cs_code',
            'supervendor_code',
            'material_description',)


class FilterHardwareControlForm(ModelForm):
    hardware = forms.ModelChoiceField(queryset=Hardware.objects.all(), required=False)
    serial = forms.CharField(required=False)

    class Meta:
        model = HardwareControl
        fields = '__all__'

hardware/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
TemplateView,
ListView,
DetailView,
UpdateView,
CreateView,
DeleteView,
FormView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from .models import Hardware, HardwareControl
from .forms import FilterHardwareForm, FilterHardwareControlForm
from .resources import HardwareResource, HardwareControlResource
from django.http import HttpResponse
import operator
from django.db.models import Q
from functools import reduce


class HardwareList(LoginRequiredMixin, ListView, FormView):
    login_url = 'users:home'
    model = Hardware
    template_name = 'hardware/hardware_list.html'
    paginate_by = 15
    form_class = FilterHardwareForm

    def get_paginate_by(self, queryset):
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super(HardwareList, self).get_context_data(**kwargs)
        context['items'] = self.get_queryset
        context['all_items'] = str(Hardware.objects.all().count())
        context['paginate_by'] = self.request.GET.get('paginate_by', self.paginate_by)
        context['query'] = self.request.GET.get('qs')
        return context


class HardwareSearch(HardwareList):

    def get_queryset(self):
        queryset = super(HardwareSearch, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            queryset = queryset.filter(
                reduce(operator.and_,
                       (Q(id__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(hardware_category__name__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(cs_code__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(supervendor_code__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(material_description__icontains=q) for q in query_list))
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HardwareSearch, self).get_context_data(**kwargs)
        context['result'] = self.get_queryset().count()
        return context


class HardwareFilter(HardwareList):
    query_dict = {}

    def get_queryset(self):
        queryset = super(HardwareFilter, self).get_queryset()
        request_dict = self.request.GET.dict()
        query_dict = {k: v for k, v in request_dict.items() if v if k != 'page' if k != 'paginate_by'}
        self.query_dict = query_dict
        queryset = queryset.filter(**query_dict)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HardwareFilter, self).get_context_data(**kwargs)
        context['query_dict'] = self.query_dict
        context['result'] = self.get_queryset().count()
        return context


def export_hardware(request):
    hardware_resource = HardwareResource()
    query_dict = request.GET.dict()
    queryset = Hardware.objects.filter(**query_dict)
    dataset = hardware_resource.export(queryset)
    response = HttpResponse(dataset.xlsx, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Hardware.xlsx"'
    return response


class HardwareControlList(LoginRequiredMixin, ListView, FormView):
    login_url = 'users:home'
    model = HardwareControl
    template_name = 'hardware_control/hardware_control_list.html'
    paginate_by = 15
    form_class = FilterHardwareControlForm

    def get_paginate_by(self, queryset):
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super(HardwareControlList, self).get_context_data(**kwargs)
        context['items'] = self.get_queryset
        context['all_items'] = str(HardwareControl.objects.all().count())
        context['paginate_by'] = self.request.GET.get('paginate_by', self.paginate_by)
        context['query'] = self.request.GET.get('qs')
        return context


class HardwareControlSearch(HardwareControlList):

    def get_queryset(self):
        queryset = super(HardwareControlSearch, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            queryset = queryset.filter(
                reduce(operator.and_,
                       (Q(id__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(hardware__cs_code__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(serial__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(site__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(hardware_state__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(active_avantel__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(state_avantel__icontains=q) for q in query_list))
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HardwareControlSearch, self).get_context_data(**kwargs)
        context['result'] = self.get_queryset().count()
        return context


class HardwareControlFilter(HardwareControlList):
    query_dict = {}

    def get_queryset(self):
        queryset = super(HardwareControlFilter, self).get_queryset()
        request_dict = self.request.GET.dict()
        query_dict = {k: v for k, v in request_dict.items() if v if k != 'page' if k != 'paginate_by'}
        self.query_dict = query_dict
        queryset = queryset.filter(**query_dict)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HardwareControlFilter, self).get_context_data(**kwargs)
        context['query_dict'] = self.query_dict
        context['result'] = self.get_queryset().count()
        return context


def export_hardware_control(request):
    hardware_control_resource = HardwareControlResource()
    query_dict = request.GET.dict()
    queryset = HardwareControl.objects.filter(**query_dict)
    dataset = hardware_control_resource.export(queryset)
    response = HttpResponse(dataset.xlsx, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Hardware.xlsx"'
    return response

hardware/templates/dashboard/includes/partials/filter.html
{% load crispy_forms_tags %}
<nav class="col-md-2 d-none bg-light filter border p-2 mt-5">
  <div class="filter-sticky">
    <form method="get" action="" onsubmit="return filter_url (this)" accept-charset="utf-8">
      <div class="form-group">
        {{ form|crispy }}
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-secondary">Filter</button>
      </div>
    </form>
  </div>
</nav>

hardware/templates/dashboard/includes/partials/nav_paginate.html
{% load filter_tags %}
{% if is_paginated %}
  <form class="form-inline" action="." method="get" id="paginate_by">
    <div class="form-group mb-3">
      <label>items per page</label>
      <div class="col-sm-1">
      <select class="form-control form-control-sm" name="paginate_by">
        <option value="15" {% if paginate_by == '15' %}selected{% endif %}>15</option>
        <option value="25" {% if paginate_by == '25' %}selected{% endif %}>25</option>
        <option value="50" {% if paginate_by == '50' %}selected{% endif %}>50</option>
        <option value="75" {% if paginate_by == '75' %}selected{% endif %}>75</option>
        <option value="100" {% if paginate_by == '100' %}selected{% endif %}>100</option>
        <option value="{{ all_items }}" {% if paginate_by == all_items %}selected{% endif %}>Todos</option>
      </select>
      </div>
    </div>
  </form>
  <p class="mr-3">{{ page_obj.start_index }} a {{ page_obj.end_index }} de {{ page_obj.paginator.count }}</p>
  <nav aria-label="Page navigation">
  <ul class="pagination justify-content-left">
    {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="{% relative_url page_obj.previous_page_number 'page' request.GET.urlencode %}">&laquo;</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
    {% endif %}

    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="{% relative_url page_obj.next_page_number 'page' request.GET.urlencode %}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><a class="page-link" href="#"><span>&raquo;</span></a></li>
    {% endif %}
  </ul>
  </nav>
{% else %}
<form class="form-inline" action="." method="get" id="paginate_by">
  <div class="form-group mb-3">
    <label>items per page</label>
    <div class="col-sm-1">
    <select class="form-control form-control-sm" name="paginate_by">
        <option value="15" {% if paginate_by == '15' %}selected{% endif %}>15</option>
        <option value="25" {% if paginate_by == '25' %}selected{% endif %}>25</option>
        <option value="50" {% if paginate_by == '50' %}selected{% endif %}>50</option>
        <option value="75" {% if paginate_by == '75' %}selected{% endif %}>75</option>
        <option value="100" {% if paginate_by == '100' %}selected{% endif %}>100</option>
        <option value="{{ all_items }}" {% if paginate_by == all_items %}selected{% endif %}>Todos</option>
    </select>
    </div>
  </div>
</form>
<p class="mr-3">{{ page_obj.start_index }} a {{ page_obj.end_index }} de {{ page_obj.paginator.count }}</p>
{% endif %}

hardware/templates/dashboard/includes/partials/navbar.html
{% load static %}
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'users:home' %}">
    <img src="{% static 'vendor/img/logo.svg' %}" width="25" height="25" class="d-inline-block align-top" alt="">
    SyF Hardware
  </a>
  <div class="">
    <a class="nav-link btn btn-dark" href="#" id="sidebar-toggle"><span data-feather="menu"></span></a>
  </div>
  <div class="w-100">
    <form class="form-inline" action="" onsubmit="return search_url (this)" method="get" accept-charset="utf-8">
      <div class="form-group w-100">
        <input type="text" class="form-control form-control-dark w-100" name="q" placeholder="Buscar" required>
      </div>
    </form>
  </div>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{% url 'users:logout' %}">{{ user.get_full_name }} <span data-feather="log-out"></span></a>
    </li>
  </ul>
</nav>

hardware/templates/dashboard/includes/partials/sidebar.html
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
      {% if perms.users.is_superuser %}
      <li class="nav-item">
        <a {% if request.resolver_match.url_name == 'admin' %}class="nav-link active"{% else %}class="nav-link"{% endif %} href="{% url 'admin:login' %}" target="blank">
          <span data-feather="database"></span>
          Admin <span class="sr-only">(current)</span>
        </a>
      </li>
      {% endif %}
      <li class="nav-item">
          <a {% if request.resolver_match.url_name == 'hardware_control_list' %}class="nav-link active"{% else %}class="nav-link"{% endif %} href="{% url 'hardware:hardware_control_list' %}">
            <span data-feather="grid"></span>
            Hardware Control<span class="sr-only">(current)</span>
          </a>
      </li>
      <li class="nav-item">
          <a {% if request.resolver_match.url_name == 'point_list' %}class="nav-link active"{% else %}class="nav-link"{% endif %} href="{% url 'meetings:point_list' %}">
            <span data-feather="check-square"></span>
            Meetings<span class="sr-only">(current)</span>
          </a>
      </li>
      <li class="nav-item">
          <a {% if request.resolver_match.url_name == 'site_list' %}class="nav-link active"{% else %}class="nav-link"{% endif %} href="{% url 'sites:site_list' %}">
            <span data-feather="cpu"></span>
            Sites<span class="sr-only">(current)</span>
          </a>
      </li>
    </ul>
  </div>
</nav>